version: '3.8'

services:
  ssh-server:
    # Alih-alih 'image', kita gunakan 'build' untuk membuat image dari Dockerfile
    build:
      context: ./ubuntu-ssh # Path ke direktori yang berisi Dockerfile
      args:
        # Kirim variabel SSH_PASSWORD dari file .env ke Dockerfile saat build
        - SSH_PASSWORD=${SSH_PASSWORD}
    container_name: ubuntu-ssh-server
    restart: unless-stopped
    volumes:
      # Membuat home directory user persisten
      - ./ssh-home:/home/dockeruser

  playit-tunnel:
    image: debian:slim-buster
    container_name: playit-ssh-tunnel
    working_dir: /data
    environment:
      - PLAYIT_AGENT_SECRET=${PLAYIT_AGENT_SECRET}
    volumes:
      - ./playit-data:/data
    command: >
      bash -c "
        if [ ! -f ./playit ]; then
          curl -sSL 'https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64' -o playit && chmod +x playit;
        fi;
        echo 'Starting playit tunnel for SSH...';
        # Arahkan tunnel ke layanan 'ssh-server' di port 22
        ./playit -secret ${PLAYIT_AGENT_SECRET} --auto-create-tunnel --tcp ssh-server:22
      "
    depends_on:
      - ssh-server
    restart: unless-stopped
